config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins

  resources :costumes
  root 'costumes#index'

  resources :admin_costumes do
    collection do
      get :fetch
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costume.rb
# frozen_string_literal: true

class Costume < ApplicationRecord
  validates :original_image_url, presence: true
  validates :title, presence: true
  validates :object_url, presence: true

  mount_uploader :picture, PictureUploader

  before_save :blank_to_nil
  before_validation :download_picture

  def self.import(object_id)
    costume = Costume.initialize_by_object_id(object_id)
    costume.save
  end

  def self.initialize_by_object_id(object_id)
    response = CostumeApiClient.return_json(object_id)
    Costume.new(
      object_id: response['objectID'],
      original_image_url: response['primaryImage'],
      title: response['title'],
      culture: response['culture'],
      country: response['country'],
      region: response['region'],
      object_url: response['objectURL'],
      date: response['objectDate']
    )
  end

  def self.initialize_by_title_url(title_url)
    response = CostumeApiClient.get_image_url(title_url)
    Costume.new(
      original_image_url: response.dig('query', 'pages', '-1', 'imageinfo')[0]['url'],
      title: response.dig('query', 'pages', '-1', 'title').delete('ファイル:'),
      object_url: response.dig('query', 'pages', '-1', 'imageinfo')[0]['descriptionurl']
    )
  end

  private

  def blank_to_nil
    self.title_japanese = nil if title_japanese.blank?
  end

  def download_picture
    return if picture.present?

    self.remote_picture_request_header = { 'Cookie' => 'incap_ses_637_1661977=c/kVUPxdLlTS2aSFBhXXCL2/YlwAAAAA90oj00SriHlKwXMQX45xkg==' }
    self.remote_picture_url = original_image_url
  end
end

app/models/costume_api_client.rb
# frozen_string_literal: true

class CostumeApiClient
  def self.return_json(object_id)
    response = Faraday.get "https://collectionapi.metmuseum.org/public/collection/v1/objects/#{object_id}"
    JSON.parse(response.body)
  end

  def self.get_image_url(title_url)
    uri = URI.parse(title_url).path.sub(%r{/wiki/File:(.+)\??}, '\1')
    title = CGI.unescape(uri)
    response = Faraday.get 'https://ja.wikipedia.org/w/api.php', format: 'json', action: 'query', titles: "Image:#{title}", prop: 'imageinfo', iiprop: 'url'
    JSON.parse(response.body)
  end
end

app/controllers/admin_costumes_controller.rb
# frozen_string_literal: true

class AdminCostumesController < ApplicationController
  def index
    @costumes = Costume.all
    @costumes = @costumes.where(continent: params[:continent]) if params[:continent].present?
    if params[:culture_or_country].present?
      @costumes = @costumes
                  .where(country_japanese: params[:culture_or_country])
                  .or(Costume.where(culture_japanese: params[:culture_or_country]))
    end
    @costumes = Costume.where(title_japanese: nil) if params[:no_title_japanese].present?
    @costumes = @costumes.order('updated_at DESC').page(params[:page]).per(15)
  end

  def fetch; end

  def destroy
    @costume = Costume.find(params[:id])
    @costume.destroy
    redirect_to admin_costumes_path, notice: 'コスチュームを削除しました。'
  end

  def edit
    @costume = Costume.find(params[:id])
  end

  def new
    @costume = if params[:object_id].include?('https')
                 Costume.initialize_by_title_url(params[:object_id])
               else
                 Costume.initialize_by_object_id(params[:object_id])
               end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/costumes_controller.rb
# frozen_string_literal: true

class CostumesController < ApplicationController
  def index
    @costumes = Costume.where.not(title_japanese: nil)
    @costumes = @costumes.where(continent: params[:continent]) if params[:continent].present?
    if params[:culture_or_country].present?
      @costumes = @costumes
                  .where(country_japanese: params[:culture_or_country])
                  .or(Costume.where(culture_japanese: params[:culture_or_country]))
    end
    @costumes = @costumes.order('random()').page(params[:page]).per(20)
  end

  def create
    @costume = Costume.new(costume_params)
    if @costume.save
      redirect_to admin_costumes_path, notice: 'コスチュームを保存しました'
    else
      render action: 'new'
    end
  end

  def update
    @costume = Costume.find(params[:id])
    if @costume.update(costume_params)
      redirect_to admin_costumes_path, notice: 'コスチュームを更新しました。'
    else
      render action: 'edit'
    end
  end

  def show
    @costume = Costume.find(params[:id])
  end

  private

  def costume_params
    params.require(:costume).permit(
      :object_id,
      :original_image_url,
      :title,
      :title_japanese,
      :culture,
      :culture_japanese,
      :country,
      :country_japanese,
      :region,
      :region_japanese,
      :object_url,
      :continent,
      :date,
      :date_japanese
      )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/costumes_helper.rb
# frozen_string_literal: true

module CostumesHelper
  def extract_culture_and_country_from_costumes(continent)
    Costume.where(continent: continent)
           .select(:country_japanese, :culture_japanese)
           .group(:country_japanese, :culture_japanese)
           .map do |costume|
      if costume.country_japanese.present?
        costume.country_japanese
      else
        costume.culture_japanese
      end
    end.uniq.compact
  end
end

app/views/admin_costumes/_form.html.slim
div class= 'costume-items'
  div class = 'costume-item'
    = image_tag(@costume.original_image_url, width: 260, class: 'costume-image')
  div class = 'costume-item'
    div class='form'
    .form-items
      = form_with(model: @costume, local: true) do |f|
        .form-item
          = f.label :object_id, class: 'label'
          = f.text_field :object_id, class: 'input'
        .form-item
          = f.label :original_image_url, class: 'label'
          = f.text_field :original_image_url, class: 'input'
        .form-item
          = f.label :title, class: 'label'
          = f.text_field :title, class: 'input'
        .form-item
          = f.label :title_japanese, class: 'label'
          = f.text_field :title_japanese, class: 'input'
        .form-item
          = f.label :culture, class: 'label'
          = f.text_field :culture, class: 'input'
        .form-item
          = f.label :culture_japanese, class: 'label'
          = f.text_field :culture_japanese, class: 'input'
        .form-item
          = f.label :country, class: 'label'
          = f.text_field :country, class: 'input'
        .form-item
          = f.label :country_japanese, class: 'label'
          = f.text_field :country_japanese, class: 'input'
        .form-item
          = f.label :region, class: 'label'
          = f.text_field :region, class: 'input'
        .form-item
          = f.label :region_japanese, class: 'label'
          = f.text_field :region_japanese, class: 'input'
        .form-item
          = f.label :date, class: 'label'
          = f.text_field :date, class: 'input'
        .form-item
          = f.label :date_japanese, class: 'label'
          = f.text_field :date_japanese, class: 'input'
        .form-item
          = f.label :object_url, class: 'label'
          = f.text_field :object_url, class: 'input'
        .form-item class='select'
          = f.label :continent, class: 'label'
          = f.select :continent, %i[アジア オセアニア ヨーロッパ アフリカ 北アメリカ 南アメリカ]
        div class='buttons'
          .form-item
            = f.submit class: 'button is-link'
            = link_to 'キャンセル', admin_costumes_path, class: 'button is-text'

app/views/admin_costumes/_form.slim
div class= 'costume-items'
  div class = 'costume-item'
    = image_tag(@costume.original_image_url, width: 260, class: 'costume-image')
  div class = 'costume-item'
    div class='form'
    .form-items
      = form_with(model: @costume, local: true) do |f|
        .form-item
          = f.label :object_id, class: 'label'
          = f.text_field :object_id, class: 'input'
        .form-item
          = f.label :original_image_url, class: 'label'
          = f.text_field :original_image_url, class: 'input'
        .form-item
          = f.label :title, class: 'label'
          = f.text_field :title, class: 'input'
        .form-item
          = f.label :title_japanese, class: 'label'
          = f.text_field :title_japanese, class: 'input'
        .form-item
          = f.label :culture, class: 'label'
          = f.text_field :culture, class: 'input'
        .form-item
          = f.label :culture_japanese, class: 'label'
          = f.text_field :culture_japanese, class: 'input'
        .form-item
          = f.label :country, class: 'label'
          = f.text_field :country, class: 'input'
        .form-item
          = f.label :country_japanese, class: 'label'
          = f.text_field :country_japanese, class: 'input'
        .form-item
          = f.label :region, class: 'label'
          = f.text_field :region, class: 'input'
        .form-item
          = f.label :region_japanese, class: 'label'
          = f.text_field :region_japanese, class: 'input'
        .form-item
          = f.label :date, class: 'label'
          = f.text_field :date, class: 'input'
        .form-item
          = f.label :date_japanese, class: 'label'
          = f.text_field :date_japanese, class: 'input'
        .form-item
          = f.label :object_url, class: 'label'
          = f.text_field :object_url, class: 'input'
        .form-item class='select'
          = f.label :continent, class: 'label'
          = f.select :continent, %i[アジア オセアニア ヨーロッパ アフリカ 北アメリカ 南アメリカ]
        div class='buttons'
          .form-item
            = f.submit class: 'button is-link'
            = link_to 'キャンセル', admin_costumes_path, class: 'button is-text'

app/views/admin_costumes/_navbar.html.slim
    header
      nav class="navbar" role="navigation" aria-label="main navigation"
        div class="layout navbar-brand"
          ul class="layout__top navbar-menu"
            li = link_to 'Traclo Top', costumes_path, class: 'navbar-item'
            li = link_to 'Admin Top', admin_costumes_path, class: 'navbar-item'
            li = link_to '新規作成', 'admin_costumes/fetch', class: 'navbar-item'
            li = link_to '未翻訳一覧', admin_costumes_path(no_title_japanese: true), class: 'navbar-item'

app/views/admin_costumes/_navbar.slim
    header
      nav class="navbar" role="navigation" aria-label="main navigation"
        div class="layout navbar-brand"
          ul class="layout__top navbar-menu"
            li = link_to 'Traclo Top', costumes_path, class: 'navbar-item'
            li = link_to 'Admin Top', admin_costumes_path, class: 'navbar-item'
            li = link_to '新規作成', 'admin_costumes/fetch', class: 'navbar-item'
            li = link_to '未翻訳一覧', admin_costumes_path(no_title_japanese: true), class: 'navbar-item'

app/views/admin_costumes/edit.html.slim
p Edit
div
  = render 'form'
  = link_to admin_costume_path, data: { confirm: "本当によろしいですか？" }, method: :delete, class: 'button is-danger'
   | 削除

app/views/admin_costumes/edit.slim
p Edit
div
  = render 'form'
  = link_to admin_costume_path, data: { confirm: "本当によろしいですか？" }, method: :delete, class: 'button is-danger'
   | 削除

app/views/admin_costumes/fetch.html.slim
= render 'navbar'
div class='fetch_form'
  = form_with(url: new_admin_costume_path, method: :get, local: true) do
    = text_field_tag :object_id, '', class: 'index__form--text-feild input'
    = submit_tag 'Fetch Object', class: 'button is-link '

app/views/admin_costumes/fetch.slim
= render 'navbar'
div class='fetch_form'
  = form_with(url: new_admin_costume_path, method: :get, local: true) do
    = text_field_tag :object_id, '', class: 'index__form--text-feild input'
    = submit_tag 'Fetch Object', class: 'button is-link '

app/views/admin_costumes/index.html.slim
doctype html
html
  head
    meta charset="utf-10"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title traclo
  body
      = render 'navbar'
  container
    div class="has-background-light"
      div class="layout columns"
        div class="layout__side column is-narrow" style="width: 160px;"
          ul class="continents"
            li
              = link_to 'アジア', admin_costumes_path(continent: 'アジア')
            li
              = link_to 'オセアニア', admin_costumes_path(continent: 'オセアニア')
            li
              = link_to 'ヨーロッパ', admin_costumes_path(continent: 'ヨーロッパ')
            li
              = link_to 'アフリカ', admin_costumes_path(continent: 'アフリカ')
            li
              = link_to '北アメリカ', admin_costumes_path(continent: '北アメリカ')
            li
              = link_to '南アメリカ', admin_costumes_path(continent: '南アメリカ')
          ul class="countries"
            - extract_culture_and_country_from_costumes(params[:continent]).each do |culture_or_country|
              li = link_to culture_or_country, admin_costumes_path(culture_or_country: culture_or_country, continent: params[:continent])
        div class="layout__main column"
          nav class="pagination" role="navigation" aria-label="pagination"
            = paginate @costumes
          table class="costumes-items"
            thead
              th イメージ
              th Object Id
              th Title
              th Title Japanese
              th Date
              th 最終更新日
            tbody
              - @costumes.each do |costume|
                tr class="costume-item"
                  td = link_to cl_image_tag(costume.picture, width: 120, crop: 'fill', class: 'admin-image'), edit_admin_costume_path(costume)
                  td = costume.object_id
                  td = costume.title
                  td = costume.title_japanese
                  td = costume.date
                  td = costume.updated_at.strftime('%Y年%-m月%-d日 %-H時%-M分')
                  td = link_to '編集', edit_admin_costume_path(costume), class:'button is-primary'
                  td = link_to '削除', admin_costume_path(costume), data: { confirm: '本当によろしいですか？' }, method: :delete, class: 'button is-danger'
          nav class="pagination" role="navigation" aria-label="pagination"
            = paginate @costumes

app/views/admin_costumes/index.slim
doctype html
html
  head
    meta charset="utf-10"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title traclo
  body
      = render 'navbar'
  container
    div class="has-background-light"
      div class="layout columns"
        div class="layout__side column is-narrow" style="width: 160px;"
          ul class="continents"
            li
              = link_to 'アジア', admin_costumes_path(continent: 'アジア')
            li
              = link_to 'オセアニア', admin_costumes_path(continent: 'オセアニア')
            li
              = link_to 'ヨーロッパ', admin_costumes_path(continent: 'ヨーロッパ')
            li
              = link_to 'アフリカ', admin_costumes_path(continent: 'アフリカ')
            li
              = link_to '北アメリカ', admin_costumes_path(continent: '北アメリカ')
            li
              = link_to '南アメリカ', admin_costumes_path(continent: '南アメリカ')
          ul class="countries"
            - extract_culture_and_country_from_costumes(params[:continent]).each do |culture_or_country|
              li = link_to culture_or_country, admin_costumes_path(culture_or_country: culture_or_country, continent: params[:continent])
        div class="layout__main column"
          nav class="pagination" role="navigation" aria-label="pagination"
            = paginate @costumes
          table class="costumes-items"
            thead
              th イメージ
              th Object Id
              th Title
              th Title Japanese
              th Date
              th 最終更新日
            tbody
              - @costumes.each do |costume|
                tr class="costume-item"
                  td = link_to cl_image_tag(costume.picture, width: 120, crop: 'fill', class: 'admin-image'), edit_admin_costume_path(costume)
                  td = costume.object_id
                  td = costume.title
                  td = costume.title_japanese
                  td = costume.date
                  td = costume.updated_at.strftime('%Y年%-m月%-d日 %-H時%-M分')
                  td = link_to '編集', edit_admin_costume_path(costume), class:'button is-primary'
                  td = link_to '削除', admin_costume_path(costume), data: { confirm: '本当によろしいですか？' }, method: :delete, class: 'button is-danger'
          nav class="pagination" role="navigation" aria-label="pagination"
            = paginate @costumes

app/views/admin_costumes/new.html.slim
p New
div
  = render 'form'

app/views/admin_costumes/new.slim
p New
div
  = render 'form'

app/views/costumes/_header.html.slim
a 
  = link_to 'Traclo', costumes_path, class:"header_logo"
p 営利・非営利利用可能な衣装の画像を探すサイト

app/views/costumes/_header.slim
a 
  = link_to 'Traclo', costumes_path, class:"header_logo"
p 営利・非営利利用可能な衣装の画像を探すサイト

app/views/costumes/index.html.slim
header
  = render 'header'
container
  .layout.columns
    .layout__side.column.menu.is-2-desktop
      ul.continents.menu-list
        li
          = link_to 'アジア', costumes_path(continent: 'アジア')
        li
          = link_to 'オセアニア', costumes_path(continent: 'オセアニア')
        li
          = link_to 'ヨーロッパ', costumes_path(continent: 'ヨーロッパ')
        li
          = link_to 'アフリカ', costumes_path(continent: 'アフリカ')
        li
          = link_to '北アメリカ', costumes_path(continent: '北アメリカ')
        li
          = link_to '南アメリカ', costumes_path(continent: '南アメリカ')
          ul.coutries.menu-list
            - extract_culture_and_country_from_costumes(params[:continent]).each do |culture_or_country|
              li = link_to culture_or_country, costumes_path(culture_or_country: culture_or_country, continent: params[:continent])
    .layout__main.column.is-8-desktop
      .pagination
        nav.pagination.is-centered role="navigation" aria-label="pagination"
          = paginate @costumes
      .search-results__results-container
        - @costumes.each do |costume|
          .search-results__results-item.card
            .search-results__results-image.card-image
              figure.image
                = link_to costume
                  = cl_image_tag costume.picture, width: 260, crop: 'fill', class: 'result-image'
            .card-content
              .search-results__results-title
                - if costume.title_japanese.present?
                  = costume.title_japanese
                - else
                  = costume.title
              .search-results__results-culture
                - if costume.country_japanese.present?
                  = costume.country_japanese + ' ' + costume.region_japanese
                - else
                  = costume.country + ' ' + costume.region
                - if costume.culture_japanese.present?
                  = costume.culture_japanese
                - else
                  = costume.culture
              .search-results__results-date
                - if costume.date_japanese.present?
                  = costume.date_japanese
                - else
                  = costume.date
      .pagination
        nav.pagination role="navigation" aria-label="pagination"
          = paginate @costumes

app/views/costumes/index.slim
div class="has-background-light"
  header
    = render 'header'
  container
    div class="layout columns"
      div class="layout__side column is-narrow" style="width: 160px;"
        ul class="continents"
          li
            = link_to 'アジア', costumes_path(continent: 'アジア')
          li
            = link_to 'オセアニア', costumes_path(continent: 'オセアニア')
          li
            = link_to 'ヨーロッパ', costumes_path(continent: 'ヨーロッパ')
          li
            = link_to 'アフリカ', costumes_path(continent: 'アフリカ')
          li
            = link_to '北アメリカ', costumes_path(continent: '北アメリカ')
          li
            = link_to '南アメリカ', costumes_path(continent: '南アメリカ')
        ul class="coutries"
          - extract_culture_and_country_from_costumes(params[:continent]).each do |culture_or_country|
            li = link_to culture_or_country, costumes_path(culture_or_country: culture_or_country, continent: params[:continent])
      div class="layout__main column"
        nav class="pagination" role="navigation" aria-label="pagination"
          = paginate @costumes
        div class="search-results__results-container"
          - @costumes.each do |costume|
            div class="search-results__results-item"
              div class="search-results__results-image"
                = link_to costume
                  = cl_image_tag costume.picture, width: 260, crop: 'fill', class: 'result-image'
              div class="search-results__results-title"
                - if costume.title_japanese.present?
                  = costume.title_japanese
                - else
                  = costume.title
              div class="search-results__results-culture"
                - if costume.country_japanese.present?
                  = costume.country_japanese + ' ' + costume.region_japanese
                - else
                  = costume.country + ' ' + costume.region
                - if costume.culture_japanese.present?
                  = costume.culture_japanese
                - else
                  = costume.culture
              div class="search-results__results-date"
                - if costume.date_japanese.present?
                  = costume.date_japanese
                - else
                  = costume.date
        nav class="pagination" role="navigation" aria-label="pagination"
          = paginate @costumes

app/views/costumes/show.html.slim
p show

a 
  = link_to @costume.object_url
    = cl_image_tag @costume.picture, width: 600, crop: 'fill', class: 'result-image'

app/views/costumes/show.slim
p show

a 
  = link_to @costume.object_url
    = cl_image_tag @costume.picture, width: 600, crop: 'fill', class: 'result-image'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traclo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=PT+Serif:700" rel="stylesheet">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>